version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: concert_ticketing_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: concert_ticketing
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/main/ressources/db/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql:ro
      - ./src/main/ressources/db/data.sql:/docker-entrypoint-initdb.d/2_data.sql:ro

volumes:
  db_data:
